In [1]:
import jax
import jax.numpy as jnp
from jax_ffi_example import forces

In [2]:
a = jax.random.uniform(jax.random.key(0), 100)
b = jax.random.uniform(jax.random.key(1), 100)

c = forces.multiply(a, b)

print(jnp.allclose(c, a*b))

True


In [ ]:
pos = jax.random.normal(jax.random.key(0), (10000,3))
mass = jnp.ones_like(pos[...,0]) 

force = forces.cuda_force(pos, mass, softening=0.1)
force2 = forces.jax_force(pos, mass, softening=0.1)
force3 = forces.simple_cuda_force(pos, mass, softening=0.1, gap=0)

print(jnp.allclose(force, force2, atol=1e-2))
print(jnp.allclose(force, force3, atol=1e-2))

True
True


In [4]:
print(force3[0:3])

[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


In [5]:
print(force[0:3])
print(force2[0:3])

[[ -789.49744 -1019.4522    214.36922]
 [  208.1288   -300.90164  1898.6261 ]
 [ 1015.1494   -888.07623 -1355.0645 ]]
[[ -789.49817 -1019.4524    214.36937]
 [  208.12854  -300.90164  1898.6234 ]
 [ 1015.1482   -888.0765  -1355.0642 ]]


In [ ]:
forces.direct_force_scan_jax(pos, mass)

Array([-3759.9348, -6841.912 , -6889.0493, ..., -5073.953 , -6592.333 ,
       -4737.787 ], dtype=float32)